apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: procurve-modern
  namespace: procurve-modern
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: procurve.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: procurve-modern
                port:
                  number: 80
